from __future__ import annotations

import json
import logging
import os
import tempfile
import threading
import uuid
from pathlib import Path
from typing import Callable

import gi

gi.require_version("Gio", "2.0")
gi.require_version("GLib", "2.0")
from gi.repository import Gio, GLib  # noqa: E402

from poed import config

from .base import Rect, Shortcut
from .capture import (
    crop_workspace_output,
    decode_kwin_frame,
    monitor_scale_factor,
    workspace_rect_physical,
)

_LOG = logging.getLogger("waystone.desktop.kwin")

SERVICE = "io.github.kriskruse.waystone.KWin"
OBJECT = "/io/github/kriskruse/waystone/KWin"
IFACE = "io.github.kriskruse.waystone.KWin"

_REQUEST_NAME_REPLY_PRIMARY_OWNER = 1
_DBUS_REQUEST_NAME_DO_NOT_QUEUE = 4
_PORTAL_BUS = "org.freedesktop.portal.Desktop"
_PORTAL_PATH = "/org/freedesktop/portal/desktop"
_PORTAL_SCREENSHOT_IFACE = "org.freedesktop.portal.Screenshot"
_PORTAL_REQUEST_IFACE = "org.freedesktop.portal.Request"

_TRACKER_XML = f"""\
<node>
  <interface name="{IFACE}">
    <method name="Hello">
      <arg name="message" type="s" direction="in"/>
    </method>
    <method name="Present">
      <arg name="present" type="b" direction="in"/>
    </method>
    <method name="Focus">
      <arg name="focused" type="b" direction="in"/>
    </method>
    <method name="Output">
      <arg name="name" type="s" direction="in"/>
    </method>
    <method name="Geometry">
      <arg name="output" type="s" direction="in"/>
      <arg name="win_x" type="i" direction="in"/>
      <arg name="win_y" type="i" direction="in"/>
      <arg name="win_w" type="i" direction="in"/>
      <arg name="win_h" type="i" direction="in"/>
      <arg name="out_x" type="i" direction="in"/>
      <arg name="out_y" type="i" direction="in"/>
      <arg name="out_w" type="i" direction="in"/>
      <arg name="out_h" type="i" direction="in"/>
    </method>
    <method name="CursorPos">
      <arg name="x" type="i" direction="in"/>
      <arg name="y" type="i" direction="in"/>
    </method>
    <method name="Hotkey">
      <arg name="shortcut_id" type="s" direction="in"/>
    </method>
  </interface>
</node>
"""


def _variant_dict(value) -> dict:
    try:
        variant = value[0] if isinstance(value, tuple) else value
        unpacked = variant.unpack()
        if unpacked and isinstance(unpacked[0], dict):
            return unpacked[0]
    except (AttributeError, IndexError, TypeError, ValueError):
        pass
    return {}


def _build_script(game_class: str) -> str:
    game_class_json = json.dumps(game_class.lower())
    return f"""// Auto-generated by Kwaystone. Do not edit.
var SERVICE = "{SERVICE}";
var OBJECT = "{OBJECT}";
var IFACE = "{IFACE}";
var GAME_CLASS = {game_class_json};

function isPoeWindow(w) {{
  if (!w) return false;
  var cap = w.caption || "";
  var cls = (w.resourceClass || "").toLowerCase();
  var name = (w.resourceName || "").toLowerCase();
  if (cls === GAME_CLASS || name === GAME_CLASS) return true;
  if (cls === "steam" || name === "steamwebhelper") return false;
  return cap === "Path of Exile 2";
}}

function call(method) {{
  var args = Array.prototype.slice.call(arguments, 1);
  callDBus.apply(null, [SERVICE, OBJECT, IFACE, method].concat(args));
}}

function listWindows() {{
  if (workspace.windowList) return workspace.windowList();
  if (workspace.clientList) return workspace.clientList();
  return [];
}}

function activeWindow() {{
  return workspace.activeWindow || workspace.activeClient || null;
}}

function outputName(w) {{
  var out = w && w.output;
  if (!out) return "";
  if (out.name !== undefined) return "" + out.name;
  return "";
}}

function rectValue(g, primary, secondary) {{
  if (!g) return 0;
  if (g[primary] !== undefined) return g[primary] | 0;
  if (secondary && g[secondary] !== undefined) return g[secondary] | 0;
  return 0;
}}

function rectWidth(g) {{
  if (!g) return 0;
  if (g.width !== undefined) return g.width | 0;
  if (g.right !== undefined && g.left !== undefined) return (g.right - g.left) | 0;
  return 0;
}}

function rectHeight(g) {{
  if (!g) return 0;
  if (g.height !== undefined) return g.height | 0;
  if (g.bottom !== undefined && g.top !== undefined) return (g.bottom - g.top) | 0;
  return 0;
}}

function valueOrCall(obj, name) {{
  if (!obj) return null;
  var v = obj[name];
  if (typeof v === "function") return v.call(obj);
  return v || null;
}}

function outputGeometry(w) {{
  var out = w && w.output;
  var g = valueOrCall(out, "geometry");
  if (!g) g = valueOrCall(out, "rect");
  if (!g) return null;
  return {{
    x: rectValue(g, "x", "left"),
    y: rectValue(g, "y", "top"),
    width: rectWidth(g),
    height: rectHeight(g)
  }};
}}

function frameGeometry(w) {{
  return valueOrCall(w, "frameGeometry");
}}

function findPoeWindow() {{
  var wins = listWindows();
  for (var i = 0; i < wins.length; i++) {{
    if (isPoeWindow(wins[i])) return wins[i];
  }}
  return null;
}}

var poeWindow = null;

function cursorInside(w) {{
  if (!w || !workspace.cursorPos) return false;
  var g = frameGeometry(w);
  if (!g) return false;
  var p = workspace.cursorPos;
  return p.x >= g.x && p.x < g.x + g.width && p.y >= g.y && p.y < g.y + g.height;
}}

function poeShouldOwnHotkeys() {{
  var active = activeWindow();
  return isPoeWindow(active);
}}

function emitState() {{
  var active = activeWindow();
  var w = isPoeWindow(active) ? active : poeWindow;
  var output = outputName(w);
  var pos = workspace.cursorPos;
  call("Present", !!poeWindow);
  call("Focus", poeShouldOwnHotkeys());
  call("Output", output || "");
  var fg = frameGeometry(w);
  var og = outputGeometry(w);
  if (fg && og && output) {{
    call(
      "Geometry",
      output,
      rectValue(fg, "x", "left"),
      rectValue(fg, "y", "top"),
      rectWidth(fg),
      rectHeight(fg),
      og.x,
      og.y,
      og.width,
      og.height
    );
  }}
  if (pos) call("CursorPos", pos.x | 0, pos.y | 0);
}}

function trackPoe(w) {{
  poeWindow = w;
  emitState();
  if (!w) return;
  if (w.frameGeometryChanged) w.frameGeometryChanged.connect(emitState);
  if (w.activeChanged) w.activeChanged.connect(emitState);
  if (w.outputChanged) w.outputChanged.connect(emitState);
  if (w.closed) {{
    w.closed.connect(function () {{
      poeWindow = findPoeWindow();
      emitState();
    }});
  }}
}}

call("Hello", "tracker loaded");
trackPoe(findPoeWindow());

var added = workspace.windowAdded || workspace.clientAdded;
if (added) {{
  added.connect(function (w) {{
    if (isPoeWindow(w)) trackPoe(w);
  }});
}}

var activated = workspace.windowActivated || workspace.clientActivated;
if (activated) activated.connect(emitState);

if (workspace.cursorPosChanged) workspace.cursorPosChanged.connect(emitState);

"""


def _build_esc_script() -> str:
    """Tiny script that binds Esc and nothing else.

    Loaded only while a Kwaystone panel is visible: a statically bound global
    Esc would be consumed by the compositor and never reach the game. Load/
    unload windows only affect Esc itself — the Alt+Z/Alt+X bindings live in
    the GlobalShortcuts portal and are never touched here.
    """
    return f"""// Auto-generated by Kwaystone. Do not edit.
registerShortcut(
  "waystone-panel-close",
  "Kwaystone: Close PoE2 overlay panel",
  "Esc",
  function () {{
    callDBus("{SERVICE}", "{OBJECT}", "{IFACE}", "Hotkey", "panel-close");
  }}
);
"""


class _KwinScript:
    """Load/run/stop/unload one declarative KWin script file via DBus."""

    def __init__(self, bus: Gio.DBusConnection | None, path: Path) -> None:
        self._bus = bus
        self._path = path
        self.script_id: int | None = None
        self.loaded = False

    def load(self, content: str) -> None:
        if self._bus is None:
            return
        self.unload()
        self._path.write_text(content)
        loaded = self._bus.call_sync(
            "org.kde.KWin",
            "/Scripting",
            "org.kde.kwin.Scripting",
            "loadScript",
            GLib.Variant("(s)", (str(self._path),)),
            GLib.VariantType.new("(i)"),
            Gio.DBusCallFlags.NONE,
            2000,
            None,
        )
        script_id = loaded.unpack()[0]
        if script_id < 0:
            raise RuntimeError("KWin refused to load Kwaystone script")
        self.script_id = int(script_id)
        self._bus.call_sync(
            "org.kde.KWin",
            f"/Scripting/Script{self.script_id}",
            "org.kde.kwin.Script",
            "run",
            None,
            None,
            Gio.DBusCallFlags.NONE,
            2000,
            None,
        )
        self.loaded = True

    def unload(self) -> None:
        if not self.loaded or self._bus is None:
            return
        try:
            if self.script_id is not None:
                self._bus.call_sync(
                    "org.kde.KWin",
                    f"/Scripting/Script{self.script_id}",
                    "org.kde.kwin.Script",
                    "stop",
                    None,
                    None,
                    Gio.DBusCallFlags.NONE,
                    2000,
                    None,
                )
            self._bus.call_sync(
                "org.kde.KWin",
                "/Scripting",
                "org.kde.kwin.Scripting",
                "unloadScript",
                GLib.Variant("(s)", (str(self._path),)),
                GLib.VariantType.new("(b)"),
                Gio.DBusCallFlags.NONE,
                2000,
                None,
            )
        except GLib.Error as e:
            _LOG.warning("KWin script unload failed: %s", e)
        self.reset()

    def reset(self) -> None:
        """Forget load state without DBus calls (the old KWin is gone)."""
        self.loaded = False
        self.script_id = None


class KWinBackend:
    name = "kwin"
    # Alt+Z/Alt+X come from the XDG GlobalShortcuts portal; Esc stays native
    # (see _build_esc_script). The portal is not required: on failure the app
    # keeps running with hotkeys degraded instead of dying.
    uses_portal_shortcuts = True
    portal_required = False

    def __init__(self, cfg: dict):
        self.cfg = cfg
        self._on_activated: Callable[[str], None] | None = None
        self._bus: Gio.DBusConnection | None = None
        self._node_info = Gio.DBusNodeInfo.new_for_xml(_TRACKER_XML)
        self._registration_id = 0
        self._script_path: Path | None = None
        self._esc_path: Path | None = None
        self._tracker: _KwinScript | None = None
        self._esc: _KwinScript | None = None
        self._esc_lock = threading.Lock()
        self._esc_seq = 0
        self._esc_thread: threading.Thread | None = None
        self._reload_thread: threading.Thread | None = None
        self._kwin_watch = 0
        self._kwin_owner: str | None = None
        self.portal_error: str | None = None
        self._panel_visible = False
        self._focused = False
        self._present = False
        self._active_output = ""
        self._game_rect_output = ""
        self._game_rect_global: Rect | None = None
        self._output_rect_global: Rect | None = None
        self._cursor: tuple[int, int] | None = None
        self._shortcuts = {
            "price-check": Shortcut(
                "price-check", "PoE2 price check", cfg["hotkey_price"]
            ),
            "unique-scan": Shortcut(
                "unique-scan", "Scan current PoE2 screen", "ALT+x"
            ),
            "arb-check": Shortcut(
                "arb-check", "Currency arbitrage", cfg["hotkey_arb"]
            ),
            "panel-close": Shortcut(
                "panel-close", "Close PoE2 overlay panel", "ESC"
            ),
        }

    def portal_shortcuts(self) -> list[tuple[str, str, str]]:
        # panel-close is intentionally absent: a statically bound Esc would be
        # consumed globally and never reach the game. It is bound natively
        # only while a panel is visible (set_panel_visible).
        return [
            (s.sid, s.description, s.trigger)
            for s in (
                self._shortcuts["price-check"],
                self._shortcuts["unique-scan"],
                self._shortcuts["arb-check"],
            )
        ]

    def portal_session_token(self) -> str | None:
        # Stable token: the KDE portal derives the kglobalaccel component from
        # it ("token_kwaystone"), so the first-run permission grant persists
        # and later launches rebind silently. Shortcuts stay user-editable in
        # System Settings.
        return "kwaystone"

    def start(self, on_activated: Callable[[str], None]) -> None:
        self._on_activated = on_activated
        self._bus = Gio.bus_get_sync(Gio.BusType.SESSION, None)
        self._request_name()
        iface = self._node_info.interfaces[0]
        self._registration_id = self._bus.register_object(
            OBJECT, iface, self._on_method_call, None, None
        )
        tmp = Path(tempfile.gettempdir())
        self._script_path = tmp / f"waystone-kwin-{os.getpid()}.js"
        self._esc_path = tmp / f"waystone-kwin-esc-{os.getpid()}.js"
        self._tracker = _KwinScript(self._bus, self._script_path)
        self._esc = _KwinScript(self._bus, self._esc_path)
        # One-time migration cleanup of shortcut entries leaked by the
        # script-era implementation; the portal path never creates these.
        # Off the main thread: it's 1s+ of D-Bus startup doesn't need.
        threading.Thread(
            target=self._cleanup_legacy_shortcuts_once, daemon=True
        ).start()
        self._load_tracker()
        self._check_portal()
        # KWin restarts silently drop loaded scripts; watch the bus name so the
        # tracker (game presence/geometry/focus) survives compositor restarts.
        self._kwin_watch = Gio.bus_watch_name_on_connection(
            self._bus,
            "org.kde.KWin",
            Gio.BusNameWatcherFlags.NONE,
            self._on_kwin_appeared,
            None,
        )

    def _check_portal(self) -> None:
        """Preflight the GlobalShortcuts portal so a broken host surfaces in
        the log and control window at startup, not on the first hotkey press.
        This probe must never raise: a failure here degrades hotkeys, it must
        not abort startup."""
        try:
            ret = self._bus.call_sync(
                "org.freedesktop.portal.Desktop",
                "/org/freedesktop/portal/desktop",
                "org.freedesktop.DBus.Properties",
                "Get",
                GLib.Variant(
                    "(ss)", ("org.freedesktop.portal.GlobalShortcuts", "version")
                ),
                GLib.VariantType.new("(v)"),
                Gio.DBusCallFlags.NONE,
                2000,
                None,
            )
        except GLib.Error as e:
            self.portal_error = f"GlobalShortcuts portal unavailable: {e.message}"
            _LOG.error("%s — Alt+Z/Alt+X hotkeys will not work", self.portal_error)
            return
        # PyGObject unpacks (v) tuples already unboxed on some versions and
        # boxed on others; accept either rather than assuming.
        value = ret.unpack()[0]
        version = value.unpack() if hasattr(value, "unpack") else value
        _LOG.info("GlobalShortcuts portal available (version %s)", version)

    def stop(self) -> None:
        if self._kwin_watch:
            Gio.bus_unwatch_name(self._kwin_watch)
            self._kwin_watch = 0
        if self._esc_thread is not None:
            # Let an in-flight Esc bind/unbind finish before final unload.
            self._esc_thread.join(timeout=2.0)
            self._esc_thread = None
        if self._esc is not None:
            self._esc.unload()
        if self._tracker is not None:
            self._tracker.unload()
        for path in (self._script_path, self._esc_path):
            if path is not None:
                try:
                    path.unlink()
                except OSError:
                    pass
        self._script_path = None
        self._esc_path = None
        if self._bus is not None:
            if self._registration_id:
                self._bus.unregister_object(self._registration_id)
                self._registration_id = 0
            self._release_name()

    def on_shortcuts_bound(self) -> None:
        return

    def set_panel_visible(self, visible: bool) -> None:
        visible = bool(visible)
        if visible == self._panel_visible:
            return
        self._panel_visible = visible
        if self._esc is None:
            return
        # Script load/unload is sync D-Bus (worst case ~4s): it must not run
        # on the GTK main loop at the moment the user waits for the panel.
        # Serialized worker; only the latest requested state is applied.
        self._esc_seq += 1
        seq = self._esc_seq

        def work():
            with self._esc_lock:
                if seq != self._esc_seq:
                    return
                try:
                    if visible:
                        self._esc.load(_build_esc_script())
                    else:
                        self._esc.unload()
                except (GLib.Error, OSError, RuntimeError) as e:
                    _LOG.warning("Esc binding failed (panel-close degraded): %s", e)

        self._esc_thread = threading.Thread(target=work, daemon=True)
        self._esc_thread.start()

    def is_game_focused(self) -> bool:
        return self._focused

    def active_game_output(self) -> str | None:
        if self._active_output:
            return self._active_output
        if self._bus is None:
            return None
        try:
            ret = self._bus.call_sync(
                "org.kde.KWin",
                "/KWin",
                "org.kde.KWin",
                "activeOutputName",
                None,
                GLib.VariantType.new("(s)"),
                Gio.DBusCallFlags.NONE,
                1000,
                None,
            )
            name = ret.unpack()[0]
            return name or None
        except GLib.Error:
            return None

    def active_game_rect(self, output: str, frame_size: tuple[int, int]) -> Rect | None:
        if (
            not output
            or output != self._game_rect_output
            or self._game_rect_global is None
            or self._output_rect_global is None
        ):
            return None
        frame_w, frame_h = frame_size
        out = self._output_rect_global
        win = self._game_rect_global
        if frame_w <= 0 or frame_h <= 0 or out.w <= 0 or out.h <= 0:
            return None

        ix0 = max(win.x, out.x)
        iy0 = max(win.y, out.y)
        ix1 = min(win.x + win.w, out.x + out.w)
        iy1 = min(win.y + win.h, out.y + out.h)
        if ix1 <= ix0 or iy1 <= iy0:
            return None

        sx = frame_w / out.w
        sy = frame_h / out.h
        rect = Rect(
            int(round((ix0 - out.x) * sx)),
            int(round((iy0 - out.y) * sy)),
            int(round((ix1 - ix0) * sx)),
            int(round((iy1 - iy0) * sy)),
        )
        return rect.clipped(frame_w, frame_h)

    def active_output_rect(self) -> Rect | None:
        return self._output_rect_global

    def capture_output(self, output: str):
        if self._bus is None or not output:
            return None
        try:
            with tempfile.TemporaryFile() as tmp:
                fd_list = Gio.UnixFDList.new()
                handle = fd_list.append(tmp.fileno())
                params = GLib.Variant("(sa{sv}h)", (output, {}, handle))
                ret = self._bus.call_with_unix_fd_list_sync(
                    "org.kde.KWin.ScreenShot2",
                    "/org/kde/KWin/ScreenShot2",
                    "org.kde.KWin.ScreenShot2",
                    "CaptureScreen",
                    params,
                    GLib.VariantType.new("(a{sv})"),
                    Gio.DBusCallFlags.NONE,
                    5000,
                    fd_list,
                    None,
                )
                tmp.seek(0)
                data = tmp.read()
            metadata = _variant_dict(ret)
        except GLib.Error as e:
            _LOG.warning("KWin screenshot failed, trying desktop portal: %s", e)
            return self._capture_portal(output)
        except OSError as e:
            _LOG.warning("KWin screenshot failed, trying desktop portal: %s", e)
            return self._capture_portal(output)
        return decode_kwin_frame(data, metadata)

    def _crop_portal_output(self, image, output: str):
        # Portal frames are physical pixels: both crop spaces must be
        # physical too (per-monitor scale applied), or fractional/mixed
        # scaling crops the wrong region.
        workspace = workspace_rect_physical()
        target = self._output_rect_global
        if (
            workspace is None
            or target is None
            or output != self._game_rect_output
            or workspace.w <= 0
            or workspace.h <= 0
        ):
            return image
        scale = monitor_scale_factor(output)
        target_physical = Rect(
            int(round(target.x * scale)),
            int(round(target.y * scale)),
            int(round(target.w * scale)),
            int(round(target.h * scale)),
        )
        return crop_workspace_output(image, workspace, target_physical)

    def _capture_portal(self, output: str):
        """Fallback for direct AppImage launches without KWin DBus permission.

        The portal owns user consent and returns a file URI. Omitting the
        version-3 target option preserves each backend's compatible legacy
        non-interactive behavior. Installed desktop entries retain the faster
        ScreenShot2 path above.
        """
        if self._bus is None:
            return None
        try:
            import cv2
            import numpy as np
        except ImportError:
            return None

        token = "waystone_" + uuid.uuid4().hex
        try:
            unique = self._bus.get_unique_name()
            sender = unique.lstrip(":").replace(".", "_")
            expected = f"{_PORTAL_PATH}/request/{sender}/{token}"
        except (AttributeError, TypeError):
            return None

        done = threading.Event()
        response: dict[str, object] = {}

        def on_response(_conn, _sender, _path, _iface, _signal, params, _data):
            try:
                code, results = params.unpack()
                response["code"] = int(code)
                response["results"] = results
            finally:
                done.set()

        subscription = 0
        try:
            subscription = self._bus.signal_subscribe(
                _PORTAL_BUS,
                _PORTAL_REQUEST_IFACE,
                "Response",
                expected,
                None,
                Gio.DBusSignalFlags.NONE,
                on_response,
                None,
            )
            options = {
                "handle_token": GLib.Variant("s", token),
                "interactive": GLib.Variant("b", False),
            }
            ret = self._bus.call_sync(
                _PORTAL_BUS,
                _PORTAL_PATH,
                _PORTAL_SCREENSHOT_IFACE,
                "Screenshot",
                GLib.Variant("(sa{sv})", ("", options)),
                GLib.VariantType.new("(o)"),
                Gio.DBusCallFlags.NONE,
                5000,
                None,
            )
            request_path = ret.unpack()[0]
            if request_path != expected:
                self._bus.signal_unsubscribe(subscription)
                subscription = self._bus.signal_subscribe(
                    _PORTAL_BUS,
                    _PORTAL_REQUEST_IFACE,
                    "Response",
                    request_path,
                    None,
                    Gio.DBusSignalFlags.NONE,
                    on_response,
                    None,
                )
            if not done.wait(15.0):
                _LOG.warning("desktop portal screenshot timed out")
                return None
        except (GLib.Error, OSError, AttributeError, TypeError, ValueError) as e:
            _LOG.warning("desktop portal screenshot failed: %s", e)
            return None
        finally:
            if subscription:
                try:
                    self._bus.signal_unsubscribe(subscription)
                except (GLib.Error, AttributeError):
                    pass

        if response.get("code") != 0:
            _LOG.warning("desktop portal screenshot was cancelled or denied")
            return None
        results = response.get("results")
        if not isinstance(results, dict):
            return None
        uri_value = results.get("uri")
        uri = uri_value.unpack() if hasattr(uri_value, "unpack") else uri_value
        if not isinstance(uri, str) or not uri:
            return None
        screenshot = Gio.File.new_for_uri(uri)
        try:
            ok, contents, _etag = screenshot.load_contents(None)
        except GLib.Error as e:
            _LOG.warning("could not read desktop portal screenshot: %s", e)
            return None
        finally:
            try:
                screenshot.delete(None)
            except GLib.Error:
                pass
        if not ok or not contents:
            return None
        image = cv2.imdecode(np.frombuffer(contents, np.uint8), cv2.IMREAD_COLOR)
        if image is None:
            return None
        return self._crop_portal_output(image, output)

    def cursor_pos(self) -> tuple[int, int] | None:
        return self._cursor

    def monitor_origin_at(self, gx: int, gy: int) -> tuple[int, int]:
        try:
            gi.require_version("Gdk", "4.0")
            from gi.repository import Gdk

            monitors = Gdk.Display.get_default().get_monitors()
            for i in range(monitors.get_n_items()):
                mon = monitors.get_item(i)
                if mon is None:
                    continue
                geo = mon.get_geometry()
                if geo.x <= gx < geo.x + geo.width and geo.y <= gy < geo.y + geo.height:
                    return geo.x, geo.y
        except Exception:
            pass
        return (0, 0)

    def _on_method_call(
        self,
        _conn,
        _sender,
        _object_path,
        _interface_name,
        method_name,
        parameters,
        invocation,
    ) -> None:
        data = parameters.unpack()
        if method_name == "Hello":
            _LOG.info("script: %s", data[0])
        elif method_name == "Present":
            self._present = bool(data[0])
            if not self._present:
                self._focused = False
                self._game_rect_output = ""
                self._game_rect_global = None
                self._output_rect_global = None
        elif method_name == "Focus":
            self._focused = bool(data[0])
        elif method_name == "Output":
            self._active_output = data[0] or ""
        elif method_name == "Geometry":
            self._game_rect_output = data[0] or ""
            self._game_rect_global = Rect(
                int(data[1]), int(data[2]), int(data[3]), int(data[4])
            )
            self._output_rect_global = Rect(
                int(data[5]), int(data[6]), int(data[7]), int(data[8])
            )
        elif method_name == "CursorPos":
            self._cursor = (int(data[0]), int(data[1]))
        elif method_name == "Hotkey":
            self._dispatch_hotkey(data[0])
        invocation.return_value(GLib.Variant("()", ()))

    def _request_name(self) -> None:
        assert self._bus is not None
        ret = self._bus.call_sync(
            "org.freedesktop.DBus",
            "/org/freedesktop/DBus",
            "org.freedesktop.DBus",
            "RequestName",
            GLib.Variant("(su)", (SERVICE, _DBUS_REQUEST_NAME_DO_NOT_QUEUE)),
            GLib.VariantType.new("(u)"),
            Gio.DBusCallFlags.NONE,
            1000,
            None,
        )
        if ret.unpack()[0] != _REQUEST_NAME_REPLY_PRIMARY_OWNER:
            raise RuntimeError(f"DBus name already in use: {SERVICE}")

    def _release_name(self) -> None:
        assert self._bus is not None
        try:
            self._bus.call_sync(
                "org.freedesktop.DBus",
                "/org/freedesktop/DBus",
                "org.freedesktop.DBus",
                "ReleaseName",
                GLib.Variant("(s)", (SERVICE,)),
                GLib.VariantType.new("(u)"),
                Gio.DBusCallFlags.NONE,
                1000,
                None,
            )
        except GLib.Error:
            pass

    def _dispatch_hotkey(self, shortcut_id: str) -> None:
        # Focus gating happens here (not in registration): scan/price presses
        # only act while the game or one of our panels owns the screen, but the
        # registrations themselves stay stable so no press hits a re-bind gap.
        if shortcut_id != "panel-close" and not (self._focused or self._panel_visible):
            _LOG.info("hotkey ignored (game not focused): %s", shortcut_id)
            return
        _LOG.info("hotkey: %s", shortcut_id)
        if self._on_activated is not None:
            self._on_activated(shortcut_id)

    def _on_kwin_appeared(self, _bus, _name, owner, *_a) -> None:
        # The watch fires once at registration for the already-running KWin;
        # only an owner change means a real compositor restart.
        if self._kwin_owner is None:
            self._kwin_owner = owner
            return
        if owner == self._kwin_owner:
            return
        self._kwin_owner = owner
        _LOG.info("KWin restarted; reloading scripts")
        self._reload_thread = threading.Thread(
            target=self._reload_scripts, daemon=True
        )
        self._reload_thread.start()

    def _reload_scripts(self) -> None:
        # Sync D-Bus script loads; always on a worker thread, never the loop.
        assert self._tracker is not None
        assert self._esc is not None
        self._tracker.reset()
        self._esc.reset()
        try:
            self._load_tracker()
            if self._panel_visible:
                self._esc.load(_build_esc_script())
        except (GLib.Error, OSError, RuntimeError) as e:
            _LOG.warning("script reload after KWin restart failed: %s", e)

    def _load_tracker(self) -> None:
        if self._tracker is None:
            return
        self._tracker.load(_build_script(self.cfg["game_window_class"]))

    def _cleanup_legacy_shortcuts_once(self) -> None:
        """One-time migration cleanup of script-era leaked kglobalaccel entries.

        Raw org.kde.KGlobalAccel RPC is forbidden by project rule; this
        read+unregister pair is the documented exception (it ran safely
        dozens of times in production logs) and exists only to purge entries
        the pre-portal implementation leaked. Runs once per state dir, then
        never again.
        """
        marker = config.state_home() / "waystone" / "legacy-shortcuts-cleaned"
        if marker.exists():
            return
        self._clear_prior_shortcuts()
        try:
            marker.parent.mkdir(parents=True, exist_ok=True)
            marker.touch()
        except OSError:
            pass

    def _clear_prior_shortcuts(self) -> None:
        if self._bus is None:
            return
        try:
            names = self._bus.call_sync(
                "org.kde.kglobalaccel",
                "/component/kwin",
                "org.kde.kglobalaccel.Component",
                "shortcutNames",
                None,
                GLib.VariantType.new("(as)"),
                Gio.DBusCallFlags.NONE,
                1000,
                None,
            ).unpack()[0]
            ours = [name for name in names if str(name).startswith("waystone-")]
            for name in ours:
                self._bus.call_sync(
                    "org.kde.kglobalaccel",
                    "/kglobalaccel",
                    "org.kde.KGlobalAccel",
                    "unregister",
                    GLib.Variant("(ss)", ("kwin", name)),
                    None,
                    Gio.DBusCallFlags.NONE,
                    1000,
                    None,
                )
            if ours:
                _LOG.info("cleared %d stale KWin shortcuts", len(ours))
        except GLib.Error as e:
            _LOG.debug("KGlobalAccel cleanup skipped: %s", e)
