[build-system]
requires = ["setuptools>=61"]
build-backend = "setuptools.build_meta"

[project]
name = "poed"
version = "0.1.0"
requires-python = ">=3.12"
dependencies = ["PyGObject"]

[tool.setuptools]
packages = ["poed"]

[project.optional-dependencies]
dev = ["pytest"]

[tool.pytest.ini_options]
testpaths = ["tests"]
pythonpath = ["."]
